# Generated by Django 3.2.6 on 2021-09-04 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0003_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(upload_to='pics/'),
        ),
    ]
