# Generated by Django 3.2.6 on 2021-09-05 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0006_auto_20210905_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='photo_link',
            new_name='photo',
        ),
    ]
