# Generated by Django 3.2.6 on 2021-09-06 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0008_alter_image_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='category',
        ),
    ]
