# Generated by Django 3.2.6 on 2021-09-06 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0009_rename_category_name_category_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='category_name',
        ),
    ]
